# CI for openseaChest through Travis CI
language: c

env:
  global:
    secure: V9UJPPxKSMe7sccPyqy0Mzj/oVwuSno7pw/YGBDeXWYTzR428IfLac7mvxJGEcvhyGsSU5Lp/H17K9by7kr9j0Xr9kYnSjzxVe4tHaVkrXDQLazfA1p3/mJENTqBBDR9D4ZQEDo8LOPhKqWDJVtLDgWcaatke786T9+AODd5il7NOFV0UVufRlHL8RMbEUBn+e1ncE+a+4OFfIosrE0Wk5oDUVbP0FLAy2akNbINJjFDIvIdNDqtfu4PU4vLYxhFgvw3WpAa1sJdf34KoP2nkGjTtNkgLdjdSYhWejkLysnWQW9NMwwHQneMUP686o2JZjA0cD0DDKbefKqGJug96Sp2/rDH/G4sLvBd5rM3TffDUZUjPSn2SBmJ1NhrjfGWSenZAvNiWTi1yACRDrbG2zcGZ1OryCF8kGcpHcfpdwAZB0rK+S/kX/Sl3UBUvEHei8HxZN311dzV7YQ1IhIQJiRhTBUqi8oKi9k16VT/PZNuaAMWJeG6vy8Xrgpwzqj52ub6cXEh+aSqYhhcWdkC0J29kPnIo6OL8aqnOvdy6CxJceir5d/3TyE+MGT/MZTtIDEOm9iBbajshUI7PkgAyRwwav4/jmkMtfXzJDQJ9oTCyM2UJ0CiRufDQBDCsyufY/JPiKbUH53dIHYZ1PEwx6eM+1hctPxeHReYZKzNHV0=

branches:
  only:
  - master
  - develop
  - "/^v\\d+\\.\\d+(\\.\\d+)?(-\\S*)?$/"
matrix:
  include:
  - os: linux
    sudo: false
    compiler: clang
    dist: xenial
    before_script: cd Make/gcc
    script: make release
  - os: linux
    sudo: false
    compiler: gcc
    dist: xenial
    before_script: cd Make/gcc
    script: make release
    deploy:
      provider: releases
      file_glob: true
      file: openseachest_exes/*
      skip_cleanup: true
      on:
        repo: Seagate/openSeaChest
        branch: develop
        tags: true
  - os: windows
    env:
    - MSBUILD_PATH="c:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin"
    - MSDEPLOY_PATH="c:\Users\travis\build\Seagate\openSeaChest\Make\VS.2017\x64\Static-Release\*"
    before_script: 
    - cd "Make\VS.2017"
    - pwd
    script:
    - export PATH=$MSBUILD_PATH:$PATH
    - echo $PATH
    - MSBuild.exe //p:Configuration=Static-Release //p:Platform=x64

